model_path: Qwen/Qwen2.5-0.5B
dataset_path: HuggingFaceH4/MATH-500
result_path: "result/qwen2.5_0.5_base/math500_cot.json"
max_new_tokens: 500
generation_sampling:
  sampling_method_name: greedy
eos_token: 151643
max_samples: 500
prompting_mode: cot-prompting
cot_prompting:
  template: "{{ problem }} \n Explain step by step. Ensure to put the final result in \\boxed{...}"

